### PR TITLE
leaflet map added

### PR DESCRIPTION
**Pull request by SHollatz**

### CODE REVIEW

**Comment by kimmie10** [comment]
My changes in the app.js will take care of Sabine's conflicts in her app.js. What were you trying to add Sabine? As for the html, which link and script is the correct one? The master has the one with the integrity so I would generally go with that one but Sabine you have done the research so which should it be?

**Review by kimmie10 — CHANGES_REQUESTED** [review]
Looks like you forgot to pull the master and rebase your branch.   The code that you did not add doesn't match the master. Let's see if we can fix this later today.

**Comment by SHollatz** [comment]
I did not intend to make changes in app.js. If so, can you delete mine and merge app.js with master?
For leaflet I created map.js to avoid such conflicts.
I pulled the index.html before I made changes, but did not rebase. In the index.html, I just changed the links to leaflet, so that they point to files instead of online resources and added the source code files.
I will try to figure it out the conflict in the index.html later. Thanks guys.

**Review by SHollatz — COMMENTED** [review]
Please review my changes. Hope I could fix the issues.

**Review by dtwelve89 — APPROVED** [review]

**Review by kimmie10 — APPROVED** [review]

**Pull request merged**
